version: "3"
services:
  postgresql:
    container_name: postgresql
    env_file:
      - ${BE_ENV_PATH}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    init: true
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: on-failure:3
    tty: true
  nginx:
    container_name: nginx_gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    init: true
    image: nginx:latest
    ports:
      - "80:80"
    restart: on-failure:3
    tty: true
    volumes:
      - "${NGINX_PATH}:/etc/nginx/conf.d"
  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "${REDIS_PATH}/data/:/data/"
  #     - "${REDIS_PATH}/config/:/user/local/etc/redis/"
  #   command: redis-server /user/local/etc/redis/redis.conf
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     timeout: 20s
  #     retries: 5
