groups:
  - name: InstanceDownAlert
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 15 seconds."

  - name: HighCpuUsageAlert
    rules:
      - alert: HighCpuUsage
        expr: node_load1 > 1
        for: 15s
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "High CPU usage detected on {{ $labels.instance }} of job {{ $labels.job }}."

  - name: HighMemoryUsageAlert
    rules:
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal - node_memory_MemFree - node_memory_Buffers - node_memory_Cached) / node_memory_MemTotal * 100 > 85
        for: 15s
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "High memory usage detected on {{ $labels.instance }} of job {{ $labels.job }}."

  - name: NodeMemUsageAlert
    rules:
    - alert: HostMemoryIsUnderutilized
      expr: ({__name__="node_memory_MemAvailable_bytes", instance="node-exporter:9100", job="node"} > 80)
      for: 15s
      labels:
        severity: critical
      annotations:
        summary: Host Memory is underutilized (instance {{ $labels.instance }})
        description: "Node memory is < 20% for 1 week. Consider reducing memory space. (instance {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
