route:
  receiver: 'Mail Alert'
  # group_by: ['alertname']
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: ${SENDER_EMAIL}
        auth_password: ${APP_PASSWORD}
        from: ${SENDER_EMAIL}
        to: ${RECEIVER_EMAIL}
        headers:
          subject: "Prometheus Alert"
