global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /opt/prometheus/alerts.yml

alerting:
  alertmanagers:
    - scheme: 'https'
      tls_config:
        ca_file: /etc/ssl/certs/alertmanager-selfsigned.crt
      static_configs:
        - targets: ['alertmanager:9093']


scrape_configs:
  - job_name: 'prometheus'
    scheme: 'https'
    tls_config:
      ca_file: /etc/ssl/certs/prometheus-selfsigned.crt
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
      ca_file: /etc/ssl/certs/node-exporter-selfsigned.crt
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

