FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       ca-certificates \
       openssl

COPY generate-certificate.sh .
RUN chmod +x generate-certificate.sh

CMD ["./generate-certificate.sh"]
