FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       ca-certificates \
       openssl

RUN mkdir -p /etc/ssl/certs
WORKDIR /etc/ssl/certs
COPY generate-certificate.sh .
RUN chmod +x generate-certificate.sh

CMD ["./generate-certificate.sh"]
