# Generated by Django 5.0.6 on 2024-06-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multigamerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
