# Generated by Django 5.0.6 on 2024-06-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multigamerecord',
            name='opponent1_id',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='opponent2_id',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='opponent3_id',
        ),
        migrations.RemoveField(
            model_name='singlegamerecord',
            name='opponent_id',
        ),
    ]
