# Generated by Django 5.0.6 on 2024-06-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleGameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_user_name', models.CharField(max_length=128)),
                ('goal_user_position', models.CharField(max_length=128)),
                ('ball_start_position', models.CharField(max_length=255)),
                ('ball_end_position', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ft_user.singlegamerecord')),
            ],
        ),
    ]
