# Generated by Django 5.0.6 on 2024-06-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multigamerecord',
            name='opponent1_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='opponent1_profile',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='opponent2_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='opponent2_profile',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='opponent3_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='opponent3_profile',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='singlegamerecord',
            name='opponent_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='singlegamerecord',
            name='opponent_profile',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
