# Generated by Django 5.0.6 on 2024-05-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0002_customuser_lose_customuser_win'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='two_factor_enabled',
            new_name='otp_enabled',
        ),
    ]
