# Generated by Django 5.0.6 on 2024-05-31 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0002_singlegamerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_win', models.BooleanField(default=False)),
                ('opponent1_id', models.IntegerField()),
                ('opponent2_id', models.IntegerField()),
                ('opponent3_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
