# Generated by Django 5.0.6 on 2024-06-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0002_remove_multigamerecord_opponent1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
