# Generated by Django 5.0.6 on 2024-06-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0002_multigamerecord_opponent1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
