# Generated by Django 5.0.6 on 2024-06-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ft_user",
            "0002_remove_customuser_friends_customuser_multi_nickname_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="followlist",
            name="following_username",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
