# Generated by Django 5.0.6 on 2024-06-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0002_rename_opponent_score_singlegamerecord_player1_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlegamedetail',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
