# Generated by Django 5.0.6 on 2024-06-14 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0003_alter_singlegamedetail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multigamerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='opponent1_name',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='opponent1_profile',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='opponent2_name',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='opponent2_profile',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='opponent3_name',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='opponent3_profile',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='multigamerecord',
            name='user_win',
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='game1',
            field=models.ForeignKey(blank=True, db_column='game1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game1', to='ft_user.singlegamerecord'),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='game2',
            field=models.ForeignKey(blank=True, db_column='game2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game2', to='ft_user.singlegamerecord'),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='game3',
            field=models.ForeignKey(blank=True, db_column='game3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game3', to='ft_user.singlegamerecord'),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='player1',
            field=models.ForeignKey(blank=True, db_column='player1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_multi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='player2',
            field=models.ForeignKey(blank=True, db_column='player2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_multi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='player3',
            field=models.ForeignKey(blank=True, db_column='player3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_multi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multigamerecord',
            name='player4',
            field=models.ForeignKey(blank=True, db_column='player4', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_multi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='singlegamerecord',
            name='is_tournament',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='singlegamedetail',
            name='game',
            field=models.OneToOneField(db_column='GameRecord', on_delete=django.db.models.deletion.CASCADE, to='ft_user.singlegamerecord'),
        ),
    ]
