# Generated by Django 5.0.6 on 2024-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0003_alter_followlist_user_alter_multigamerecord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlegamedetail',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
