# Generated by Django 5.0.6 on 2024-06-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0003_alter_singlegamedetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlegamedetail',
            name='game',
            field=models.OneToOneField(db_column='GameRecord', on_delete=django.db.models.deletion.CASCADE, to='ft_user.singlegamerecord'),
        ),
    ]
