# Generated by Django 5.0.6 on 2024-05-21 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0003_alter_customuser_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('step', models.PositiveIntegerField(default=30)),
                ('t0', models.BigIntegerField(default=0)),
                ('digits', models.PositiveSmallIntegerField(default=6)),
                ('tolerance', models.PositiveSmallIntegerField(default=1)),
                ('drift', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
