# Generated by Django 5.0.6 on 2024-06-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0005_alter_singlegamedetail_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlegamerecord',
            name='winner',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
