name: "기능 추가"
description: 기능 추가 Issue 작성 양식입니다.
title: "[FE/BE/COMMON/INFRA] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "[FE/BE/COMMON/INTRA] 2FA 기능 추가"
  - type: textarea
    id: feature-description
    attributes:
      label: 작업 설명
      description: 추가할 기능을 설명해주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
  - type: textarea
    id: approach
    attributes:
      label: 접근 및 구현 방법
      description: 생각한 접근법이나 구현할 방법 (구조) 등을 설명해주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: false
